version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ddd-template
    expose:
    - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433" # MyPort : ContainerPort
    volumes:
    - ./backups:/home/backups/postgres
    command: -p 5433
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001" # MyPort : ContainerPort
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - PORT=4001
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5433/ddd-template?schema=public
      - NODE_ENV=DEV
    depends_on:
      - postgres
